name       : haskell-data-default-class
version    : 0.1.2.0
release    : 3
source     :
    - http://hackage.haskell.org/package/data-default-class-0.1.2.0/data-default-class-0.1.2.0.tar.gz : 4f01b423f000c3e069aaf52a348564a6536797f31498bb85c3db4bd2d0973e56
license    : BSD-3-Clause
component  : programming.haskell
summary    : A class for types with a default value
description: |
    A class for types with a default value
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
